#ifndef LANGUAGE_H
#define LANGUAGE_H

#include <Arduino.h>

#define LANG_ENGLISH 0
#define LANG_INDONESIAN 1

struct LangEntry {
  const char* key;
  const char* en;
  const char* id;
};

static const LangEntry langTable[] = {
  {"app_name", "NETHERCAP", "NETHERCAP"},
  {"scan", "Scan", "Pindai"},
  {"attack", "Attack", "Serangan"},
  {"monitor", "Monitor", "Monitor"},
  {"settings", "Settings", "Pengaturan"},
  {"files", "Files", "Berkas"},
  {"customhtml", "Custom HTML", "HTML Kustom"},
  {"language", "Language", "Bahasa"},
  {"extender", "Extender", "Extender"},
  {"select_target", "Select Target", "Pilih Target"},
  {"ssid", "SSID", "SSID"},
  {"bssid", "BSSID", "BSSID"},
  {"channel", "CH", "CH"},
  {"rssi", "RSSI", "RSSI"},
  {"vendor", "Vendor", "Vendor"},
  {"clients", "Clients", "Klien"},
  {"action", "Action", "Aksi"},
  {"selected", "SELECTED", "DIPILIH"},
  {"select", "Select", "Pilih"},
  {"start_deauth", "Start Deauth", "Mulai Deauth"},
  {"stop_deauth", "Stop Deauth", "Hentikan Deauth"},
  {"start_beacon", "Start Beacon", "Mulai Beacon"},
  {"stop_beacon", "Stop Beacon", "Hentikan Beacon"},
  {"start_probe", "Start Probe", "Mulai Probe"},
  {"stop_probe", "Stop Probe", "Hentikan Probe"},
  {"start_eviltwin", "Start EvilTwin", "Mulai EvilTwin"},
  {"stop_eviltwin", "Stop EvilTwin", "Hentikan EvilTwin"},
  {"deauth", "Deauth", "Deauth"},
  {"beacon", "Beacon", "Beacon"},
  {"probe", "Probe", "Probe"},
  {"eviltwin", "EvilTwin", "EvilTwin"},
  {"active", "ACTIVE", "AKTIF"},
  {"inactive", "INACTIVE", "TIDAK AKTIF"},
  {"no_target", "No target selected", "Tidak ada target"},
  {"captured", "Captured Passwords", "Password Tertangkap"},
  {"no_captured", "No passwords captured yet", "Belum ada password"},
  {"device_info", "Device Info", "Info Perangkat"},
  {"firmware", "Firmware", "Firmware"},
  {"board", "Board", "Board"},
  {"mac", "MAC Address", "Alamat MAC"},
  {"free_heap", "Free Heap", "Heap Bebas"},
  {"uptime", "Uptime", "Waktu Aktif"},
  {"ap_settings", "AP Settings", "Pengaturan AP"},
  {"ap_ssid", "AP SSID", "AP SSID"},
  {"ap_password", "AP Password", "Kata Sandi AP"},
  {"change", "Change", "Ubah"},
  {"reset_settings", "Reset", "Atur Ulang"},
  {"format_spiffs", "Format SPIFFS", "Format SPIFFS"},
  {"reboot", "Reboot", "Restart"},
  {"confirm_reboot", "Reboot device?", "Restart perangkat?"},
  {"confirm_reset", "Reset all settings?", "Atur ulang semua?"},
  {"confirm_format", "Format filesystem?", "Format sistem berkas?"},
  {"file_manager", "File Manager", "Manajer Berkas"},
  {"filename", "Filename", "Nama Berkas"},
  {"size", "Size", "Ukuran"},
  {"delete", "Delete", "Hapus"},
  {"upload", "Upload", "Unggah"},
  {"choose_file", "Choose File", "Pilih Berkas"},
  {"language_editor", "Language Editor", "Editor Bahasa"},
  {"key", "Key", "Kunci"},
  {"value", "Value", "Nilai"},
  {"save", "Save", "Simpan"},
  {"custom_html", "Custom Phishing Page", "Halaman Phishing Kustom"},
  {"use_custom", "Use Custom", "Gunakan Kustom"},
  {"packet_monitor", "Packet Monitor", "Monitor Paket"},
  {"packets", "Packets", "Paket"},
  {"deauth_pkts", "Deauth Packets", "Paket Deauth"},
  {"beacon_pkts", "Beacon Packets", "Paket Beacon"},
  {"probe_pkts", "Probe Packets", "Paket Probe"},
  {"warning", "WARNING", "PERINGATAN"},
  {"disclaimer", "This project is for educational purposes only. Use only against your own networks.", "Proyek ini hanya untuk tujuan edukasi. Gunakan hanya pada jaringan Anda sendiri."},
  {"agree", "I have read and understand", "Saya telah membaca dan mengerti"},
  {"ssid_count", "SSIDs", "SSID"},
  {"ch", "CH", "CH"},
  {"enc", "Enc", "Enk"},
  {"stop", "Stop", "Berhenti"},
  {"start", "Start", "Mulai"},
  {"refresh", "Refresh", "Segarkan"},
  {"connected", "Connected", "Terhubung"},
  {"disconnected", "Disconnected", "Terputus"},
  {"session_hijack", "Session Hijack", "Session Hijack"},
  {"start_hijack", "Start Hijack", "Mulai Hijack"},
  {"stop_hijack", "Stop Hijack", "Hentikan Hijack"},
  {"hijack_active", "Hijack ACTIVE", "HIJACK AKTIF"},
  {"hijack_clients", "Hijacked Clients", "Klien Hijack"},
  {"custom_animation", "Custom Animation", "Animasi Kustom"},
  {"deauth_monitor", "Deauth Monitor", "Monitor Deauth"},
  {"deauth_all", "Deauth All", "Deauth Semua"},
  {"precise_deauth", "Precise Deauth", "Deauth Presisi"},
  {"true_deauth", "True Deauth", "Deauth Sejati"},
  {"count_stations", "Count Stations", "Hitung Stasiun"},
  {"observe_stations", "Observe Stations", "Amati Stasiun"},
  {"reveal_ssid", "Reveal SSID", "Tampilkan SSID"},
  {"deep_scan", "Deep Scan", "Pindai Dalam"},
  {"hide_ssid", "Hide SSID", "Sembunyikan SSID"},
  {"ddos_router", "DDoS Router", "Router DDoS"},
  {"pattern_lock", "Pattern Lock", "Kunci Pola"},
  {"pin_lock", "PIN Lock", "Kunci PIN"},
  {"enter_pin", "Enter PIN", "Masukkan PIN"},
  {"wrong_pin", "Wrong PIN!", "PIN Salah!"},
  {"unlocked", "Unlocked", "Terbuka"},
  {"locked", "Locked", "Terkunci"},
  {"log_viewer", "Log Viewer", "Lihat Log"},
  {"no_logs", "No logs yet", "Belum ada log"},
  {"clear_logs", "Clear Logs", "Hapus Log"},
  {"battery", "Battery", "Baterai"},
  {"battery_level", "Battery: %d%%", "Baterai: %d%%"},
  {"charging", "Charging", "Mengisi"},
  {"animation_idle", "Idle Animation", "Animasi Diam"},
  {"animation_boot", "Boot Animation", "Animasi Mulai"},
  {"dark_theme", "Dark Theme", "Tema Gelap"},
  {"extender_mode", "Extender Mode", "Mode Extender"},
  {"extender_scan", "Scan for Networks", "Pindai Jaringan"},
  {"extender_connect", "Connect", "Hubungkan"},
  {"extender_status", "Extender Status", "Status Extender"},
  {"extender_clients", "Connected Clients", "Klien Terhubung"},
  {"extender_signal", "Signal: %d%%", "Sinyal: %d%%"},
  {"help", "Help", "Bantuan"},
  {"help_title", "NETHERCAP Help & Usage Guide", "Panduan Bantuan & Penggunaan NETHERCAP"},
  {"help_intro", "Welcome to NETHERCAP - a powerful WiFi auditing tool for ESP8266. Use it responsibly on your own networks only.", "Selamat datang di NETHERCAP - alat audit WiFi untuk ESP8266. Gunakan secara bertanggung jawab hanya pada jaringan Anda sendiri."},
  {"help_scan_desc", "Scan & select target networks. The scan page shows all visible WiFi networks with BSSID, channel, RSSI, and vendor info. Click Select to choose a target.", "Pindai & pilih jaringan target. Halaman pindai menampilkan semua jaringan WiFi terlihat dengan BSSID, saluran, RSSI, dan info vendor. Klik Pilih untuk memilih target."},
  {"help_attack_desc", "Launch various WiFi attacks: Deauth (disconnect clients), Beacon Spam (flood fake APs), Probe (probe request flood), Evil-Twin (rogue AP with phishing), Session Hijack, Deauth All, Precise Deauth, and True Deauth.", "Luncurkan berbagai serangan WiFi: Deauth (putuskan klien), Beacon Spam (kirim AP palsu), Probe (banjir probe), Evil-Twin (AP palsu dengan phishing), Session Hijack, Deauth Semua, Deauth Presisi, dan Deauth Sejati."},
  {"help_monitor_desc", "Monitor packet counts, view real-time logs, and track captured passwords from Evil-Twin attacks.", "Pantau jumlah paket, lihat log real-time, dan lacak kata sandi yang tertangkap dari serangan Evil-Twin."},
  {"help_settings_desc", "View device info (firmware, MAC, free heap, uptime), configure button GPIO pins, select OLED type, and manage system (reboot/reset/format).", "Lihat info perangkat (firmware, MAC, heap bebas, waktu aktif), konfigurasi pin GPIO tombol, pilih tipe OLED, dan kelola sistem (restart/atur ulang/format)."},
  {"help_extender_desc", "Extender mode - scan for external WiFi networks and share the connection through the ESP8266.", "Mode Extender - pindai jaringan WiFi eksternal dan bagikan koneksi melalui ESP8266."},
  {"help_files_desc", "Upload and manage files on the ESP8266 LittleFS filesystem. Upload custom HTML pages for phishing.", "Unggah dan kelola berkas di sistem berkas LittleFS ESP8266. Unggah halaman HTML kustom untuk phishing."},
  {"help_customhtml_desc", "Upload custom phishing HTML pages and activate them from the Attack page for use with Evil-Twin.", "Unggah halaman HTML phishing kustom dan aktifkan dari halaman Serangan untuk digunakan dengan Evil-Twin."},
  {"help_language_desc", "Switch between English and Indonesian languages. View the full translation table.", "Beralih antara bahasa Inggris dan Indonesia. Lihat tabel terjemahan lengkap."},
  {"help_attack_variants", "Additional Attacks", "Serangan Tambahan"},
  {"help_deauth_all_desc", "Deauth All - sends deauth packets to ALL visible networks simultaneously.", "Deauth Semua - kirim paket deauth ke SEMUA jaringan terlihat secara bersamaan."},
  {"help_precise_deauth_desc", "Precise Deauth - sends targeted deauth packets to a specific AP with higher success rate.", "Deauth Presisi - kirim paket deauth tertarget ke AP tertentu dengan tingkat keberhasilan lebih tinggi."},
  {"help_true_deauth_desc", "True Deauth - aggressive mode that rescans and deauths all networks continuously.", "Deauth Sejati - mode agresif yang memindai ulang dan melakukan deauth semua jaringan secara terus menerus."},
  {"help_rogue_ap_desc", "Rogue AP - creates an open 'Free WiFi' hotspot with DNS spoofing for captive portal.", "Rogue AP - buat hotspot terbuka 'Free WiFi' dengan spoofing DNS untuk portal tangkapan."},
  {"rogue_ap", "Rogue AP", "Rogue AP"},
  {"start_rogue_ap", "Start Rogue AP", "Mulai Rogue AP"},
  {"stop_rogue_ap", "Stop Rogue AP", "Hentikan Rogue AP"},
  {"internet_sharing", "Internet Sharing (NAT)", "Berbagi Internet (NAT)"},
  {"wifi_networks", "WiFi Networks", "Jaringan WiFi"},
  {"wifi_password", "WiFi Password", "Kata Sandi WiFi"},
  {"connect", "Connect", "Hubungkan"},
  {"disconnect", "Disconnect", "Putuskan"},
  {"enable_sharing", "Enable Sharing", "Aktifkan Berbagi"},
  {"disable_sharing", "Disable Sharing", "Nonaktifkan Berbagi"},
  {"scan_networks", "Scan Networks", "Pindai Jaringan"},
};

static const int langCount = sizeof(langTable) / sizeof(langTable[0]);

static String tr(const char* key, uint8_t lang) {
  for (int i = 0; i < langCount; i++) {
    if (strcmp(langTable[i].key, key) == 0) {
      return String(lang == LANG_ENGLISH ? langTable[i].en : langTable[i].id);
    }
  }
  return String(key);
}

#endif
